bogle-bogle/thepet-backend

build.gradle

fix($build): jar로 변경

---

src/main/java/com/thehyundai/thepet/cart/CartService.java
src/main/java/com/thehyundai/thepet/cart/CartServiceImpl.java
src/main/java/com/thehyundai/thepet/heendycar/HeendyCarService.java
src/main/java/com/thehyundai/thepet/heendycar/HeendyCarServiceImpl.java
src/main/java/com/thehyundai/thepet/mypet/club/ClubService.java
src/main/java/com/thehyundai/thepet/mypet/club/ClubServiceImpl.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetService.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetServiceImpl.java
src/main/java/com/thehyundai/thepet/order/OrderService.java
src/main/java/com/thehyundai/thepet/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/product/ProductService.java
src/main/java/com/thehyundai/thepet/product/ProductServiceImpl.java
src/main/java/com/thehyundai/thepet/review/ReviewService.java
src/main/java/com/thehyundai/thepet/review/ReviewServiceImpl.java
src/main/java/com/thehyundai/thepet/subscription/SubsMapper.java
src/main/java/com/thehyundai/thepet/subscription/SubsService.java
src/main/java/com/thehyundai/thepet/subscription/SubsServiceImpl.java

fix(setting): @Service 위치 변경

---

src/main/java/com/thehyundai/thepet/exception/ErrorCode.java
src/main/java/com/thehyundai/thepet/product/ProductController.java
src/main/java/com/thehyundai/thepet/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/product/ProductService.java
src/main/java/com/thehyundai/thepet/product/ProductServiceImpl.java
src/main/java/com/thehyundai/thepet/product/ProductVO.java
src/main/java/com/thehyundai/thepet/review/ReviewController.java
src/main/java/com/thehyundai/thepet/review/ReviewMapper.java
src/main/java/com/thehyundai/thepet/review/ReviewService.java
src/main/java/com/thehyundai/thepet/review/ReviewServiceImpl.java
src/main/java/com/thehyundai/thepet/review/ReviewVO.java
src/main/resources/mappers/product/Product.xml
src/main/resources/mappers/review/Review.xml

feat(product, review) : 상품, 댓글 조회

---

src/main/java/com/thehyundai/thepet/mypet/club/ClubController.java
src/main/java/com/thehyundai/thepet/mypet/club/ClubMapper.java
src/main/java/com/thehyundai/thepet/mypet/club/ClubService.java
src/main/java/com/thehyundai/thepet/mypet/club/ClubServiceImpl.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetMapper.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetService.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetServiceImpl.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetVO.java
src/main/resources/mappers/PetMapper.xml

feat(pet): 흰디클럽 가입하기 API 구현

---

src/main/java/com/thehyundai/thepet/cart/CartServiceImpl.java
src/main/java/com/thehyundai/thepet/mypet/club/ClubServiceImpl.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetController.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetMapper.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetService.java
src/main/java/com/thehyundai/thepet/mypet/pet/PetServiceImpl.java
src/main/java/com/thehyundai/thepet/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/product/ProductServiceImpl.java
src/main/java/com/thehyundai/thepet/review/ReviewServiceImpl.java
src/main/java/com/thehyundai/thepet/subscription/SubsServiceImpl.java
src/main/resources/mappers/PetMapper.xml

feat(pet): 잘 먹는 사료 변경하기 API 구현

---

src/main/java/com/thehyundai/thepet/heendycar/HcBranchVO.java

fix(heendycar): 지점 이미지URL 저장하도록 VO 수정

---

src/main/java/com/thehyundai/thepet/heendycar/HcController.java
src/main/java/com/thehyundai/thepet/heendycar/HcService.java
src/main/java/com/thehyundai/thepet/heendycar/HcServiceImpl.java
src/main/java/com/thehyundai/thepet/member/MemberServiceImpl.java
src/main/java/com/thehyundai/thepet/util/AuthTokensGenerator.java
src/main/java/com/thehyundai/thepet/util/JwtTokenProvider.java
src/main/resources/mappers/CmCodeMapper.xml

흰디카 예약하기 보완 완료

---

src/main/java/com/thehyundai/thepet/exception/ErrorCode.java
src/main/java/com/thehyundai/thepet/global/TableStatus.java
src/main/java/com/thehyundai/thepet/heendycar/HcController.java
src/main/java/com/thehyundai/thepet/heendycar/HcServiceImpl.java
src/main/java/com/thehyundai/thepet/member/MemberController.java
src/main/java/com/thehyundai/thepet/member/MemberMapper.java
src/main/java/com/thehyundai/thepet/member/MemberService.java
src/main/java/com/thehyundai/thepet/member/MemberServiceImpl.java
src/main/java/com/thehyundai/thepet/order/OrderController.java
src/main/java/com/thehyundai/thepet/order/OrderMapper.java
src/main/java/com/thehyundai/thepet/order/OrderService.java
src/main/java/com/thehyundai/thepet/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/util/AuthTokensGenerator.java

주문하기 API 구현 완료

---

src/main/java/com/thehyundai/thepet/member/MemberMapper.java
src/main/java/com/thehyundai/thepet/member/MemberServiceImpl.java
src/main/resources/mappers/MemberMapper.xml

fix(member): 회원 관련 로직 수정

---

src/main/java/com/thehyundai/thepet/product/ProductController.java
src/main/java/com/thehyundai/thepet/product/ProductListVO.java
src/main/java/com/thehyundai/thepet/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/product/ProductService.java
src/main/java/com/thehyundai/thepet/product/ProductServiceImpl.java
src/main/resources/mappers/ProductMapper.xml

feat(product): pagenation

---

Dockerfile
src/main/java/com/thehyundai/thepet/product/ProductController.java
src/main/java/com/thehyundai/thepet/product/ProductListVO.java
src/main/java/com/thehyundai/thepet/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/product/ProductService.java
src/main/java/com/thehyundai/thepet/product/ProductServiceImpl.java
src/main/resources/mappers/ProductMapper.xml

pagenation merge

---

src/main/java/com/thehyundai/thepet/SwaggerConfig.java

fix($swagger): 스웨거에서 헤더 관련 설정 변경

---

src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetServiceImpl.java

refactor: 패키지 구조 변경에 따른 import문 변경

---

src/main/java/com/thehyundai/thepet/domain/product/FilterVO.java
src/main/java/com/thehyundai/thepet/domain/product/ProductController.java
src/main/java/com/thehyundai/thepet/domain/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/domain/product/ProductService.java
src/main/java/com/thehyundai/thepet/domain/product/ProductServiceImpl.java
src/main/resources/mappers/ProductMapper.xml

feat(product): 상품 목록 필터

---

.github/workflows/create_jira_issue.yml

Github Issue와 Jira 티켓 연결

---

src/main/java/com/thehyundai/thepet/sms/HcSmsEventListener.java

fix(sms) : 코드 수정

---

build.gradle
src/main/java/com/thehyundai/thepet/aws_s3/AWSConfig.java
src/main/java/com/thehyundai/thepet/aws_s3/S3Service.java
src/main/java/com/thehyundai/thepet/aws_s3/UploadController.java

s3 업로드 백엔드 api 생성

---

src/main/java/com/thehyundai/thepet/aws_s3/UploadController.java

s3 이미지 검증 & url반환 같이

---

.github/issue-branch.yml
.github/workflows/create_branch.yml
.github/workflows/create_jira_issue.yml

Github Actions -> 브랜치 생성 및 Jira 티켓 생성

---

src/main/java/com/thehyundai/thepet/domain/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationServiceImpl.java
src/main/resources/mappers/ProductMapper.xml

fix(recommendation): 단백질원 제대로 검색되지 않는 오류 수정

---

.github/issue-branch.yml
src/main/java/com/thehyundai/thepet/domain/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationServiceImpl.java
src/main/resources/mappers/ProductMapper.xml

hotfix: 서버 오류 해결

---

src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetController.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/order/OrderController.java
src/main/java/com/thehyundai/thepet/global/cmcode/ProteinCmCode.java
src/main/resources/mappers/PetMapper.xml

feat(pet): AI 맞춤 추천 관련 로직 수정 - 잘 먹는 사료 주 단백질 성분 추출 및 저장

---

src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetController.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetService.java
src/main/java/com/thehyundai/thepet/domain/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/global/config/RedisCacheConfig.java

fix: 배포 오류 수정

---

src/main/java/com/thehyundai/thepet/domain/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/product/ProductController.java
src/main/java/com/thehyundai/thepet/domain/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/domain/product/ProductService.java
src/main/java/com/thehyundai/thepet/domain/product/ProductServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/subscription/CurationController.java
src/main/java/com/thehyundai/thepet/domain/subscription/CurationService.java
src/main/resources/mappers/ProductMapper.xml

feature(backoffice - product) : 일반 상품 등록

---

src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetServiceImpl.java

fix: 토큰 관련 코드 수정

---

src/main/java/com/thehyundai/thepet/domain/product/ProductController.java
src/main/java/com/thehyundai/thepet/domain/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/domain/product/ProductService.java
src/main/java/com/thehyundai/thepet/domain/product/ProductServiceImpl.java
src/main/resources/mappers/ProductMapper.xml

상품을 카테고리와 키워드로 검색

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java

feat(cors): cors 에러 백엔드 설정

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java

feat(cors): cors config 수정

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java

cors config 수정

---

src/main/java/com/thehyundai/thepet/domain/cart/CartController.java

fix(cart): patch -> put

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java

feat(cors): cors url 추가

---

src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetController.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetMapper.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetService.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/product/ProductMapper.java
src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationController.java
src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationServiceImpl.java
src/main/resources/mappers/PetMapper.xml
src/main/resources/mappers/ProductMapper.xml

suggesition, mbti 관련 로직 수정

---

src/main/java/com/thehyundai/thepet/ThepetApplication.java

fix: swagger 정상화

---

src/main/java/com/thehyundai/thepet/domain/cart/CartVO.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetController.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetService.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetServiceImpl.java
src/main/java/com/thehyundai/thepet/global/cmcode/CmCodeMapper.java
src/main/java/com/thehyundai/thepet/global/exception/ErrorCode.java
src/main/java/com/thehyundai/thepet/global/jwt/JwtTokenProvider.java
src/main/resources/mappers/CartMapper.xml
src/main/resources/mappers/CmCodeMapper.xml
src/main/resources/mappers/CurationMapper.xml
src/main/resources/mappers/HcBranchMapper.xml
src/main/resources/mappers/HcReservationMapper.xml
src/main/resources/mappers/MemberMapper.xml
src/main/resources/mappers/OrderDetailMapper.xml
src/main/resources/mappers/OrderMapper.xml
src/main/resources/mappers/PetMapper.xml
src/main/resources/mappers/ProductMapper.xml
src/main/resources/mappers/ReviewMapper.xml
src/main/resources/mappers/SubsMapper.xml

mapper 수정 및 jwt 토큰 관련 오류 보완

---

src/main/java/com/thehyundai/thepet/domain/heendycar/HcController.java
src/main/resources/mappers/HcReservationMapper.xml

fix: 코드 오류 수정

---

src/main/java/com/thehyundai/thepet/domain/member/MemberController.java
src/main/java/com/thehyundai/thepet/tosspayment/TossPaymentConfig.java

ci: properties 추가

---

src/main/java/com/thehyundai/thepet/domain/order/OrderController.java
src/main/java/com/thehyundai/thepet/domain/order/OrderServiceImpl.java
src/main/resources/mappers/OrderMapper.xml

feat(order) : 주문 테이블에 넣기 오류 수정

---

src/main/java/com/thehyundai/thepet/domain/heendycar/HcReservationMapper.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcServiceImpl.java
src/main/java/com/thehyundai/thepet/global/exception/ErrorCode.java
src/main/resources/mappers/HcReservationMapper.xml

feat: 이미 예약이 존재하면 예외처리

---

src/main/java/com/thehyundai/thepet/domain/cart/CartMapper.java
src/main/java/com/thehyundai/thepet/domain/order/OrderServiceImpl.java

feat(order) : 주문된 상품들은 카트에서 삭제로 업데이트

---

src/main/java/com/thehyundai/thepet/domain/member/MypageVO.java

ci: 빌드 관련 에러 수정

---

.gitignore
build.gradle
src/main/java/com/thehyundai/thepet/global/config/JasyptConfig.java
src/main/resources/application.properties

feat(application.properties) : jasypt 적용 application.properties 암호화

---

.gitignore
build.gradle
src/main/java/com/thehyundai/thepet/domain/member/MypageVO.java
src/main/java/com/thehyundai/thepet/global/config/JasyptConfig.java
src/main/resources/application.properties

properties 암호화

---

Dockerfile

fix(Dockerfile): 도커파일 jasypt 적용으로 인해 수정

---

Dockerfile

fix(Jasypt) : Dockerfile 수정

---

src/main/java/com/thehyundai/thepet/domain/cart/CartController.java

feat(cart) : put으로 수정

---

src/main/java/com/thehyundai/thepet/domain/heendycar/HcController.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcReservationMapper.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcReservationVO.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcService.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcServiceImpl.java
src/main/resources/mappers/HcReservationMapper.xml

feat(backoffice) : 흰디카 예약내역 관리자 버튼 추가

---

src/main/java/com/thehyundai/thepet/domain/cart/CartController.java
src/main/java/com/thehyundai/thepet/domain/cart/CartServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcController.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/member/MemberController.java
src/main/java/com/thehyundai/thepet/domain/member/MemberServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/mypet/club/ClubController.java
src/main/java/com/thehyundai/thepet/domain/mypet/customcard/CustomCardController.java
src/main/java/com/thehyundai/thepet/domain/mypet/customcard/CustomCardServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetController.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/order/OrderController.java
src/main/java/com/thehyundai/thepet/domain/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/product/ProductController.java
src/main/java/com/thehyundai/thepet/domain/product/ProductServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationController.java
src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/review/ReviewController.java
src/main/java/com/thehyundai/thepet/domain/review/ReviewServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/subscription/CurationController.java
src/main/java/com/thehyundai/thepet/domain/subscription/CurationServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/subscription/SubsServiceImpl.java
src/main/java/com/thehyundai/thepet/global/aws/AwsS3Controller.java

ci: 로깅 로직 임시 주석처리

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java
src/main/java/com/thehyundai/thepet/global/jwt/JwtErrorController.java
src/main/resources/application.properties

fix: swagger 설정

---

src/main/java/com/thehyundai/thepet/domain/backoffice/BackOfficeVO.java
src/main/java/com/thehyundai/thepet/domain/backoffice/BackofficeController.java
src/main/java/com/thehyundai/thepet/domain/backoffice/BackofficeMapper.java
src/main/java/com/thehyundai/thepet/domain/backoffice/BackofficeService.java
src/main/java/com/thehyundai/thepet/domain/backoffice/BackofficeServiceImpl.java
src/main/java/com/thehyundai/thepet/global/config/WebConfig.java
src/main/resources/mappers/BackofficeMapper.xml

지난달 매출액, 대분류별 비율

---

src/main/java/com/thehyundai/thepet/domain/heendycar/HcReservationVO.java
src/main/resources/mappers/HcReservationMapper.xml

feat(HeendyCar) : (백오피르,백엔드)흰디카 예약시 일련번호 지급 및 표시

---

src/main/java/com/thehyundai/thepet/domain/order/OrderDetailVO.java
src/main/java/com/thehyundai/thepet/domain/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/order/OrderVO.java
src/main/java/com/thehyundai/thepet/external/sms/PaymentSmsEvent.java
src/main/java/com/thehyundai/thepet/external/sms/PaymentSmsEventListener.java

결제 완료 문자 전송

---

src/main/resources/application.properties

fix(Redis) : 서버 분산에 따른 Redis 서버 분리

---

src/main/java/com/thehyundai/thepet/domain/heendycar/HcReservationMapper.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcServiceImpl.java
src/main/java/com/thehyundai/thepet/global/config/WebConfig.java
src/main/resources/mappers/HcReservationMapper.xml

fix(webconfig, HeendyCar) : webconfig 수정 및 흰디카 mapper 수정

---

src/main/resources/application.properties

fix(Redis) : Redis 서버 ip 변동에 따른 commit

---

build.gradle
src/main/java/com/thehyundai/thepet/domain/mypet/club/ClubController.java
src/main/java/com/thehyundai/thepet/domain/mypet/club/ClubRequestVO.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetService.java
src/main/java/com/thehyundai/thepet/domain/mypet/pet/PetServiceImpl.java
src/main/java/com/thehyundai/thepet/global/config/WebConfig.java
src/main/resources/mappers/PetMapper.xml

feat: 강아지 등록 로직 spring으로 이관

---

build.gradle
src/main/java/com/thehyundai/thepet/domain/member/MemberController.java
src/main/java/com/thehyundai/thepet/domain/member/MemberMapper.java
src/main/java/com/thehyundai/thepet/domain/member/MemberService.java
src/main/java/com/thehyundai/thepet/domain/member/MemberServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/member/MemberVO.java
src/main/java/com/thehyundai/thepet/domain/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/external/tosspayment/CardRegiDTO.java
src/main/java/com/thehyundai/thepet/external/tosspayment/CardResDTO.java
src/main/java/com/thehyundai/thepet/external/tosspayment/PaymentController.java
src/main/java/com/thehyundai/thepet/external/tosspayment/PaymentReqDTO.java
src/main/java/com/thehyundai/thepet/external/tosspayment/PaymentService.java
src/main/java/com/thehyundai/thepet/external/tosspayment/TossPaymentConfig.java
src/main/resources/application.properties
src/main/resources/mappers/MemberMapper.xml
src/main/resources/mappers/SubsMapper.xml

정기결제 카드 등록

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java

fix(webconfig): webconfig 수정

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java

webconfig 수정

---

src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationVO.java
src/main/java/com/thehyundai/thepet/global/config/WebConfig.java
src/main/resources/mappers/ProductMapper.xml

product mapper -> 상품 목록 sql 성분 컬럼 추가

---

src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationVO.java

fix(recommendation): ToString annotation 제거

---

src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationVO.java
src/main/resources/mappers/ProductMapper.xml

ToString annotation 제거

---

src/main/java/com/thehyundai/thepet/domain/heendycar/HcServiceImpl.java

fix(HeendyCar): 시큐어코딩 수정

---

src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberServiceImpl.java
src/main/resources/mappers/BackOfficeMemberMapper.xml

feat(backoffice): member masking

---

src/main/java/com/thehyundai/thepet/domain/member/MemberController.java
src/main/java/com/thehyundai/thepet/domain/member/MemberService.java
src/main/java/com/thehyundai/thepet/domain/member/MemberServiceImpl.java
src/main/java/com/thehyundai/thepet/global/config/WebConfig.java
src/main/resources/application.properties

feat(login): kakao login 알고리즘 백엔드 service에서 동작

---

src/main/java/com/thehyundai/thepet/domain/member/MemberServiceImpl.java

fix(login): login 코드 수정

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java

fix(login): 제외

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java

로그인 api 제외

---

src/main/resources/application.properties

fix(login): redirect url 수정

---

src/main/java/com/thehyundai/thepet/global/config/WebConfig.java
src/main/resources/application.properties

redirect url 수정

---

src/main/resources/mappers/EventLogMapper.xml

fix(event): event log date query 수정

---

src/main/resources/application.properties
src/main/resources/mappers/EventLogMapper.xml

event log sql query 수정

---

src/main/resources/application.properties

feat(login): properties

---

src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberController.java
src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberMapper.java
src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberService.java
src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeResMemberVO.java
src/main/resources/mappers/BackOfficeMemberMapper.xml

fix(backoffice): 백오피스 member 관리 service, mapper 코드 수정

---

src/main/resources/mappers/HcReservationMapper.xml

fix(HeendyCar) : 관리자 예약현황 정렬 수정

---

src/main/resources/application.properties

feat(login): local properties 삭제

---

src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationServiceImpl.java
src/main/java/com/thehyundai/thepet/global/cmcode/CmCode.java
src/main/java/com/thehyundai/thepet/global/timetrace/TimeTraceAspect.java
src/main/resources/application.properties

fix: 추천 알고리즘 수정

---

src/main/java/com/thehyundai/thepet/domain/recommendation/RecommendationServiceImpl.java
src/main/java/com/thehyundai/thepet/global/cmcode/CmCode.java
src/main/java/com/thehyundai/thepet/global/timetrace/TimeTraceAspect.java
src/main/resources/application.properties
src/main/resources/mappers/CartMapper.xml

추천 알고리즘 수정

---

src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/heendycar/HcServiceImpl.java

fix(backoffice): 마스킹 작업 수정

---

.gitignore
src/main/resources/mappers/PetMapper.xml

fix: 반려동물 이름 가나다순으로 정렬하도록 변경

---

src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberController.java
src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberMapper.java
src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberService.java
src/main/java/com/thehyundai/thepet/domain/backoffice/member/BackOfficeMemberServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/backoffice/member/MemberRequestVO.java
src/main/java/com/thehyundai/thepet/global/config/WebConfig.java
src/main/resources/mappers/BackOfficeMemberMapper.xml

fix(backoffice): member 날짜 설정 추가

---

src/main/java/com/thehyundai/thepet/domain/order/OrderServiceImpl.java
src/main/java/com/thehyundai/thepet/domain/subscription/CurationController.java
src/main/java/com/thehyundai/thepet/domain/subscription/CurationService.java
src/main/java/com/thehyundai/thepet/domain/subscription/CurationServiceImpl.java

feat: 다음 달로 변경
